version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope