name: "Auto merge dependabot PRs"

on:
  pull_request:

jobs:
  auto-merge:
    name: "Auto merge dependabot PRs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.CI_TOKEN }}
          command: squash and merge