name: Build App

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install React Native CLI
        run: |
          yarn global add react-native-cli
      - name: Install yarn dependencies
        run: |
          yarn install
      - name: Build bundle
        run: |
          yarn react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
      - name: Build Android
        env:
          KEYSTORE_ALIAS: ${{ secrets.STAGING_KEYSTORE_ALIAS }}
          KEYSTORE_PASSPHRASE: ${{ secrets.STAGING_KEYSTORE_PASSPHRASE }}
        run: |
          export VERSION_CODE=${{ github.run_number }}
          export VERSION_NAME=0.1.${{ github.run_number }}
          echo ${{ secrets.STAGING_KEYSTORE }} | base64 --decode > android/app/staging.keystore
          cd android && ./gradlew -PversCode=$VERSION_CODE -PversName=$VERSION_NAME :app:assembleStaging
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: android/app/build/outputs/apk/staging/app-staging.apk
